import {
  BarChart3,
  BookOpen,
  Boxes,
  ClipboardCheck,
  FileQuestion,
  GraduationCap,
  Megaphone,
  PackageSearch,
  Palette,
  ReceiptText,
  Settings,
  ShieldCheck,
  UserRoundSearch,
  Users,
} from "lucide-react";

export const navigationItems = [
  {
    label: "Command Center",
    path: "/app",
    icon: BarChart3,
    permission: "command_center.view",
    group: "Overview",
    order: 10,
  },
  {
    label: "Admissions",
    path: "/app/admissions",
    icon: UserRoundSearch,
    permission: "applications.view",
    group: "Student Lifecycle",
    order: 20,
  },
  {
    label: "Students",
    path: "/app/students",
    icon: GraduationCap,
    permission: "students.view",
    group: "Student Lifecycle",
    order: 30,
  },
  {
    label: "Academics",
    path: "/app/academics",
    icon: BookOpen,
    permission: "academics.view",
    group: "Academic Operations",
    order: 40,
  },
  {
    label: "Assessment Center",
    path: "/app/assessment-center",
    icon: FileQuestion,
    permission: "assessments.view",
    group: "Academic Operations",
    order: 45,
  },
  {
    label: "Attendance",
    path: "/app/attendance",
    icon: ClipboardCheck,
    permission: "attendance.view",
    group: "Academic Operations",
    order: 50,
  },
  {
    label: "Human Resources",
    path: "/app/human-resources",
    icon: Users,
    permission: "staff.view",
    group: "Institutional Operations",
    order: 60,
  },
  {
    label: "Finance",
    path: "/app/finance",
    icon: ReceiptText,
    permission: "finance.view",
    group: "Institutional Operations",
    order: 70,
  },
  {
    label: "Procurement",
    path: "/app/procurement",
    icon: PackageSearch,
    permission: "procurement.view",
    group: "Institutional Operations",
    order: 80,
  },
  {
    label: "Inventory & Assets",
    path: "/app/inventory",
    icon: Boxes,
    permission: "inventory.view",
    group: "Institutional Operations",
    order: 90,
  },
  {
    label: "Communications",
    path: "/app/communications",
    icon: Megaphone,
    permission: "communications.view",
    group: "Communications & Insight",
    order: 100,
  },
  {
    label: "Reports",
    path: "/app/reports",
    icon: ShieldCheck,
    permission: "reports.view",
    group: "Communications & Insight",
    order: 110,
  },
  {
    label: "Settings",
    path: "/app/settings",
    icon: Settings,
    permission: "settings.view",
    group: "Administration",
    order: 120,
  },
  {
    label: "Design Lab",
    path: "/app/design-lab",
    icon: Palette,
    permission: "design_lab.view",
    group: "Administration",
    order: 130,
  },
];